name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    uses: ./.github/workflows/launch_gradle_commands.yml
    secrets:
      BASE_URL: ${{ secrets.BASE_URL }}
      NAVER_API_APP_NAME: ${{ secrets.NAVER_API_APP_NAME }}
      NAVER_API_CLIENT_ID: ${{ secrets.NAVER_API_CLIENT_ID }}
      NAVER_API_CLIENT_SECRET: ${{ secrets.NAVER_API_CLIENT_SECRET }}
      KAKAO_KEY_MANIFEST: ${{ secrets.KAKAO_KEY_MANIFEST }}
      KAKAO_NATIVE_KEY: ${{ secrets.KAKAO_NATIVE_KEY }}
    with:
      commands: build
