name: Gradle Executable Environment

on:
  workflow_call:
    inputs:
      commands:
        required: true
        type: string
      uploadArtifacts:
        required: false
        type: boolean
    secrets:
      BASE_URL:
        description: 'base url for network'
        required: true
      NAVER_API_APP_NAME:
        description: 'naver api name for never login'
        required: true  
      NAVER_API_CLIENT_ID:
        description: 'naver api client id for never login'
        required: true   
      NAVER_API_CLIENT_SECRET:
        description: 'naver api client secret for never login'
        required: true   
jobs:
  launch_gradle_commands:
    name: Gradle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Write base_url
        env:
          API_KEY: ${{ secrets.BASE_URL }}
        run: echo base_url=\"$BASE_URL\" >> ./local.properties
        
      - name: Write NAVER_API_APP_NAME
        env:
          NAVER_API_APP_NAME: ${{ secrets.NAVER_API_APP_NAME }}
        run: echo naver_api_app_name=\"$NAVER_API_APP_NAME\" >> ./local.properties

      - name: Write NAVER_API_CLIENT_ID
        env:
          NAVER_API_CLIENT_ID: ${{ secrets.NAVER_API_CLIENT_ID }}
        run: echo naver_api_client_id=\"$NAVER_API_CLIENT_ID\" >> ./local.properties
        
      - name: Write NAVER_API_CLIENT_SECRET
        env:
          NAVER_API_CLIENT_SECRET: ${{ secrets.NAVER_API_CLIENT_SECRET }}
        run: echo naver_api_client_secret=\"$NAVER_API_CLIENT_SECRET\" >> ./local.properties

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: ${{ inputs.commands }}
